-- ---------------------------------------------------------------------------
-- Fix: Make start_sprint and complete_sprint SECURITY DEFINER
--
-- Why:
-- 1. start_sprint inserts a notification row into public.notifications.
-- 2. By default, insert on public.notifications is revoked from 'authenticated'
--    because notifications are designed to be generated by system events and
--    SECURITY DEFINER routines.
-- 3. Without SECURITY DEFINER, invoking start_sprint as an authenticated user
--    causes Postgres error 42501: "permission denied for table notifications".
-- 4. complete_sprint updates issues and sprints across team boundaries,
--    and sends completion notifications.
-- ---------------------------------------------------------------------------

create or replace function public.start_sprint(
  p_sprint uuid,
  p_start  timestamptz default now(),
  p_end    timestamptz default null
)
returns public.sprints
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_sprint public.sprints;
  v_project_id uuid;
  v_workspace_id uuid;
  v_points numeric;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated' using errcode = 'insufficient_privilege';
  end if;

  select project_id into v_project_id
    from public.sprints
   where id = p_sprint;

  if v_project_id is null then
    raise exception 'Sprint not found';
  end if;

  select workspace_id into v_workspace_id
    from public.projects
   where id = v_project_id;

  -- Permission check: verify read access to project & sprint management capability or owner
  if not public.can_read_project(v_project_id)
     or not (
       public.can_do(v_workspace_id, 'sprint.start')
       or public.can_do(v_workspace_id, 'sprint.create')
     ) then
    raise exception 'You do not have permission to start this sprint'
      using errcode = 'insufficient_privilege';
  end if;

  select coalesce(sum(i.story_points), 0) into v_points
    from public.issues i where i.sprint_id = p_sprint;

  update public.sprints
     set status = 'active',
         start_date = p_start,
         end_date = coalesce(p_end, end_date, p_start + interval '14 days'),
         committed_points = v_points
   where id = p_sprint
  returning * into v_sprint;

  if v_sprint.id is null then
    raise exception 'Sprint not found or not permitted';
  end if;

  insert into public.notifications
    (user_id, workspace_id, project_id, actor_id, type, title, body, payload)
  select m.user_id, p.workspace_id, p.id, auth.uid(), 'sprint_started',
         v_sprint.name || ' started', v_sprint.goal,
         jsonb_build_object('sprint_id', v_sprint.id, 'project_key', p.key)
    from public.projects p
    join public.workspace_members m on m.workspace_id = p.workspace_id
   where p.id = v_sprint.project_id
     and m.user_id is distinct from auth.uid();

  return v_sprint;
end;
$$;

create or replace function public.complete_sprint(
  p_sprint        uuid,
  p_target_sprint uuid default null
)
returns public.sprints
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_sprint public.sprints;
  v_project_id uuid;
  v_workspace_id uuid;
  v_completed numeric;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated' using errcode = 'insufficient_privilege';
  end if;

  select project_id into v_project_id
    from public.sprints
   where id = p_sprint;

  if v_project_id is null then
    raise exception 'Sprint not found';
  end if;

  select workspace_id into v_workspace_id
    from public.projects
   where id = v_project_id;

  if not public.can_read_project(v_project_id)
     or not (
       public.can_do(v_workspace_id, 'sprint.complete')
       or public.can_do(v_workspace_id, 'sprint.create')
     ) then
    raise exception 'You do not have permission to complete this sprint'
      using errcode = 'insufficient_privilege';
  end if;

  select coalesce(sum(i.story_points), 0) into v_completed
    from public.issues i
    join public.project_statuses s on s.id = i.status_id
   where i.sprint_id = p_sprint
     and s.category = 'done';

  -- Unfinished work rolls into the next sprint, or back to the backlog.
  update public.issues i
     set sprint_id = p_target_sprint
   where i.sprint_id = p_sprint
     and i.status_id in (
       select s.id from public.project_statuses s where s.category <> 'done'
     );

  update public.sprints
     set status = 'completed',
         completed_points = v_completed,
         completed_at = now()
   where id = p_sprint
  returning * into v_sprint;

  if v_sprint.id is null then
    raise exception 'Sprint not found or not permitted';
  end if;

  insert into public.notifications
    (user_id, workspace_id, project_id, actor_id, type, title, body, payload)
  select m.user_id, p.workspace_id, p.id, auth.uid(), 'sprint_completed',
         v_sprint.name || ' completed',
         'Completed ' || coalesce(v_completed, 0) || ' points.',
         jsonb_build_object('sprint_id', v_sprint.id, 'project_key', p.key)
    from public.projects p
    join public.workspace_members m on m.workspace_id = p.workspace_id
   where p.id = v_sprint.project_id
     and m.user_id is distinct from auth.uid();

  return v_sprint;
end;
$$;

grant execute on function public.start_sprint(uuid, timestamptz, timestamptz) to authenticated;
grant execute on function public.complete_sprint(uuid, uuid) to authenticated;
